### ISSUE TITLE
本地JS怎么保障安全

### ISSUE THREAD

**Issue by sany620** [vczero/React-Native-App#1]
本地JS怎么保障安全

**Comment by vczero** [comment]
十分安全的部分应该交由native来做。

**Comment by ghost** [comment]
在sever下执行 node app.js后：
module.js:339
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (.../React-Native-App-master/address_book/server/app.js:1:77)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

请问该如何解决？

**Comment by vczero** [comment]
在server目录下执行命令： npm install

**Comment by songbai1211** [comment]
真机不能运行，怎么办？

**Comment by vczero** [comment]
可以开启真机调试，或者需要证书打包才能跑呢
