### ISSUE TITLE
我下载下来了。但是Server跑不起来

### ISSUE THREAD

**Issue by cooliean** [vczero/React-Native-App#11]
### 然后 npm start

一直说这个错误
app.set('port', port);
    ^

TypeError: app.set is not a function

我是node 6.0.0 
# 

*_用npm install  &&  node app.js  *_
报下面的错误

Not Found

404

Error: Not Found
    at /MyPath/React-Native-App-master/address_book/server/app.js:56:17
    at Layer.handle [as handle_request](/MyPath/React-Native-App-master/address_book/server/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/MyPath/React-Native-App-master/address_book/server/node_modules/express/lib/router/index.js:302:13)
    at /MyPath/React-Native-App-master/address_book/server/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/MyPath/React-Native-App-master/address_book/server/node_modules/express/lib/router/index.js:321:12)
    at next (/MyPath/React-Native-App-master/address_book/server/node_modules/express/lib/router/index.js:261:10)
    at SendStream.error (/MyPath/React-Native-App-master/address_book/server/node_modules/serve-static/index.js:107:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/MyPath/React-Native-App-master/address_book/server/node_modules/send/index.js:250:17)

**Comment by cooliean** [comment]
明白了，本来就是个没有界面的后台，结合书上看了看，服务应该是好的，
http://127.0.0.1:3000/test/show  这个都是可以通过的，打扰了。以后又问题再来。
