### ISSUE TITLE
address_book demo报错

### ISSUE THREAD

**Issue by welken** [vczero/React-Native-App#15]
![image](https://cloud.githubusercontent.com/assets/12828290/16198839/f52b9438-3739-11e6-8d5d-18c0f541268f.png)

**Comment by leechance** [comment]
我也是同样的问题,你解决了

**Comment by vczero** [comment]
你先在React-Native-App/address_book/目录下npm。建议可以参考“厕所在哪”那个App

**Comment by wuxu** [comment]
node module报错呀，不知道什么问题，请教！
bogon:address_book wuxu$ node module 
module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/wuxu/Desktop/js_project/react_native/React-Native-App/address_book/module'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
bogon:address_book wuxu$ npm -v
3.10.3
bogon:address_book wuxu$ node -v
v6.2.2
