### ISSUE TITLE
run-ios报错

### ISSUE THREAD

**Issue by xiaodongzai** [vczero/React-Native-App#16]
```
The following build commands failed:
    Ld build/Build/Products/Debug-iphonesimulator/address_book.app/address_book normal x86_64
(1 failure)
/Users/xiezd/svn/react-native/React-Native-App/address_book/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: xcodebuild process exited with code 65
    at ChildProcess.<anonymous> (runIOS.js:102:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by xiaodongzai** [comment]
使用Xcode可以运行起来

**Comment by leechance** [comment]
我的运行不起来

**Comment by vczero** [comment]
列上你的具体步骤，然后，我再给你看

**Comment by Yetland** [comment]
RCTRootView.h怎么老是说这个不存在、?

**Comment by leechance** [comment]
@Yetland  react-native link 执行以下试试
