### ISSUE TITLE
npm install 一堆err

### ISSUE THREAD

**Issue by mvpdream** [vczero/React-Native-App#6]

**Comment by vczero** [comment]
翻墙试试

**Comment by mvpdream** [comment]
可以给个qq吗 方便联系

**Comment by mvpdream** [comment]
安卓的有很多代码需要改的 很多组件都不支持 全是错

**Comment by vczero** [comment]
嗯嗯，android有很多代码需要修改，需要修改掉带“IOS”的后缀的组件。

**Comment by vczero** [comment]
可以先发送邮件到我邮箱, 一起交流沟通

**Comment by mvpdream** [comment]
可不可以写一套安卓的代码呢

**Comment by vczero** [comment]
目前工作较忙，正在计划中....写好了，这里@你

**Comment by mvpdream** [comment]
好的  谢谢

**Comment by shaoyi52** [comment]
我也用android 出现这些问题 不知道该咋运下去了
D:\demo\React-Native-App\address_book\server>node app.js
----------listening on port: 3000----------------------
GET / 500 17.927 ms - 965
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new View (D:\demo\React-Native-App\address_book\node_modules\express\lib\
view.js:78:30)
    at EventEmitter.render (D:\demo\React-Native-App\address_book\node_modules\e
xpress\lib\application.js:569:12)
    at ServerResponse.render (D:\demo\React-Native-App\address_book\node_modules
\express\lib\response.js:961:7)
    at D:\demo\React-Native-App\address_book\server\app.js:73:11
    at Layer.handle_error (D:\demo\React-Native-App\address_book\node_modules\ex
press\lib\router\layer.js:71:5)
    at trim_prefix (D:\demo\React-Native-App\address_book\node_modules\express\l
ib\router\index.js:310:13)
GET / 500 20.230 ms - 965
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new View (D:\demo\React-Native-App\address_book\node_modules\express\lib\
view.js:78:30)
    at EventEmitter.render (D:\demo\React-Native-App\address_book\node_modules\e
xpress\lib\application.js:569:12)
    at ServerResponse.render (D:\demo\React-Native-App\address_book\node_modules
\express\lib\response.js:961:7)
    at D:\demo\React-Native-App\address_book\server\app.js:73:11
    at Layer.handle_error (D:\demo\React-Native-App\address_book\node_modules\ex
press\lib\router\layer.js:71:5)
    at trim_prefix (D:\demo\React-Native-App\address_book\node_modules\express\l
ib\router\index.js:310:13)
GET / 500 18.447 ms - 965
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new View (D:\demo\React-Native-App\address_book\node_modules\express\lib\
view.js:78:30)
    at EventEmitter.render (D:\demo\React-Native-App\address_book\node_modules\e
xpress\lib\application.js:569:12)
    at ServerResponse.render (D:\demo\React-Native-App\address_book\node_modules
\express\lib\response.js:961:7)
    at D:\demo\React-Native-App\address_book\server\app.js:73:11
    at Layer.handle_error (D:\demo\React-Native-App\address_book\node_modules\ex
press\lib\router\layer.js:71:5)
    at trim_prefix (D:\demo\React-Native-App\address_book\node_modules\express\l
ib\router\index.js:310:13)
GET / 500 16.599 ms - 965
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new View (D:\demo\React-Native-App\address_book\node_modules\express\lib\
view.js:78:30)
    at EventEmitter.render (D:\demo\React-Native-App\address_book\node_modules\e
xpress\lib\application.js:569:12)
    at ServerResponse.render (D:\demo\React-Native-App\address_book\node_modules
\express\lib\response.js:961:7)
    at D:\demo\React-Native-App\address_book\server\app.js:73:11
    at Layer.handle_error (D:\demo\React-Native-App\address_book\node_modules\ex
press\lib\router\layer.js:71:5)
    at trim_prefix (D:\demo\React-Native-App\address_book\node_modules\express\l
ib\router\index.js:310:13)

**Comment by vczero** [comment]
@shaoyi52 目前不支持Android代码，如果改造成了Android代码，可以提个pull request
